import type { Metadata } from "next";
import "./globals.css";

//fonts
import { poppins } from "./_services/fonts/fonts";

//contexts
import { AppUtils } from "./_contexts/utils";
import { AppBookingDetails } from "./_contexts/booking-details-context";

//shadcn
import { Toaster } from "./_services/components/ui/toaster";

export const metadata: Metadata = {
  title: "Barber FSW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" >
      <body className={poppins.className}>
        <AppBookingDetails>
          <AppUtils>
            {children}
            <Toaster />
          </AppUtils>
        </AppBookingDetails>
      </body>
    </html>
  );
}
