import type { Metadata } from "next";
import "./globals.css";

//fonts
import { poppins } from "./_services/fonts/fonts";

export const metadata: Metadata = {
  title: "Barber FSW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" >
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
